---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0640
    group: redis
  notify: restart redis

- name: Ensure Redis db and logs dirs access is restricted.
  file:
    dest: "{{ item }}"
    mode: 0700
  with_items:
    - "{{ redis_dbdir }}"
    - "{{ redis_logdir }}"


- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
